from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.mySpaces, name='mySpaces'),
    path('leaderSpaces/', views.leaderSpaces, name='leaderSpaces'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.space_page, name='space'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('leaderProfile/<str:id>/', views.profile, name='profile_leader'),
    path('leader/<int:code>/', views.space_page_leader, name='leader'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addReport/<int:code>/', views.addReport, name='addReport'),
    path('report/<int:code>/<int:id>/',
         views.reportPage, name='reportPage'),
    path('reports/<int:code>/', views.allReports, name='allReports'),
    path('member-reports/<int:code>/',
         views.allReportsSTD, name='member-reports'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('space-coupon/<int:code>/',
         views.addSpaceCoupon, name='addSpaceCoupon'),
    path('space-coupon/<int:code>/<int:id>/',
         views.deleteSpaceCoupon, name='deleteSpaceCoupon'),
    path('spaces/', views.spaces, name='spaces'),
    path('branches/', views.branches, name='branches'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordLeader/', views.changePasswordLeader,
         name='changePasswordLeader'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoLeader/', views.changePhotoLeader,
         name='changePhotoLeader'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]
